--- 
rvm-1.0.21.tar.gz:
  :md5: 
  :path_prefix: packages/rvm/
  :url: http://rvm.beginrescueend.com/releases/rvm-1.0.21.tar.gz
ruby-1.9.2-p0.tar.bz2:
  :md5: 755aba44607c580fddc25e7c89260460
  :path_prefix: ruby-lang/1.9/
  :url: ftp://ftp.ruby-lang.org/pub/ruby/1.9/ruby-1.9.2-p0.tar.bz2
ruby-1.9.1-p378.tar.bz2:
  :md5: 9fc5941bda150ac0a33b299e1e53654c
  :path_prefix: ruby-lang/1.9/
  :url: ftp://ftp.ruby-lang.org/pub/ruby/1.9/ruby-1.9.1-p378.tar.bz2
ruby-1.8.7-p302.tar.bz2:
  :md5: a6a9e37079ed8cf8726b455dad3de939
  :path_prefix: ruby-lang/1.8/
  :url: ftp://ftp.ruby-lang.org/pub/ruby/1.8/ruby-1.8.7-p302.tar.bz2
ruby-1.8.6-p399.tar.bz2:
  :md5: c3d16cdd3c1ee8f3b7d1c399d4884e33
  :path_prefix: ruby-lang/1.8/
  :url: ftp://ftp.ruby-lang.org/pub/ruby/1.8/ruby-1.8.6-p399.tar.bz2
ruby-1.8.5-p231.tar.bz2:
  :md5: e900cf225d55414bffe878f00a85807c
  :path_prefix: ruby-lang/1.8/
  :url: ftp://ftp.ruby-lang.org/pub/ruby/1.8/ruby-1.8.5-p231.tar.bz2
rubygems-1.3.7.tgz:
  :md5: e85cfadd025ff6ab689375adbf344bbe
  :path_prefix: rubygems/
  :url: http://rubyforge.org/frs/download.php/70696/rubygems-1.3.7.tgz
rubygems-1.3.6.tgz:
  :md5: 789ca8e9ad1d4d3fe5f0534fcc038a0d
  :path_prefix: rubygems/
  :url: http://rubyforge.org/frs/download.php/69365/rubygems-1.3.6.tgz
rubygems-1.3.5.tgz:
  :md5: 6e317335898e73beab15623cdd5f8cff
  :path_prefix: rubygems/
  :url: http://rubyforge.org/frs/download.php/60718/rubygems-1.3.5.tgz  
jruby-bin-1.5.3.tar.gz:
  :md5: ccb0b2dbc300d8dd4ad1bd4da48b8320
  :path_prefix: jruby/1.5.3/
  :url: http://jruby.org.s3.amazonaws.com/downloads/1.5.3/jruby-bin-1.5.3.tar.gz
rubinius-1.1.0-20100923.tar.gz:
  :md5: e2ae16238b201de09975abe19da09ea9
  :path_prefix: rbx/
  :url: http://asset.rubini.us/rubinius-1.1.0-20100923.tar.gz
ruby-enterprise-1.8.7-2010.02.tar.gz:
  :md5: 4df7b09c01adfd711b0ab76837611542
  :path_prefix: ree/
  :url: http://rubyforge.org/frs/download.php/71096/ruby-enterprise-1.8.7-2010.02.tar.gz
MacRuby 0.7.1.zip:
  :md5: e8245dcd03c0757dfae7e6fee913947a
  :path_prefix: macruby/
  :url: http://www.macruby.org/files/MacRuby%200.7.1.zip
readline-5.2.tar.gz:
  :md5: 
  :path_prefix: packages/readline/
  :url: ftp://ftp.gnu.org/gnu/readline/readline-5.2.tar.gz
libiconv-1.13.1.tar.gz:
  :md5: 
  :path_prefix: packages/iconv/
  :url: http://ftp.gnu.org/pub/gnu/libiconv/libiconv-1.13.1.tar.gz
curl-7.19.7.tar.gz:
  :md5: 
  :path_prefix: packages/curl/
  :url: http://curl.haxx.se/download/curl-7.19.7.tar.gz
openssl-0.9.8n.tar.gz:
  :md5: 
  :path_prefix: packages/openssl/
  :url: http://www.openssl.org/source/openssl-0.9.8n.tar.gz
zlib-1.2.5.tar.gz:
  :md5: 
  :path_prefix: packages/zlib/
  :url: http://zlib.net/zlib-1.2.5.tar.gz
autoconf-2.65.tar.gz:
  :md5: 
  :path_prefix: packages/autoconf/
  :url: ftp://ftp.gnu.org/gnu/autoconf/autoconf-2.65.tar.gz
ncurses-5.7.tar.gz:
  :md5: 
  :path_prefix: packages/ncurses/
  :url: http://ftp.gnu.org/pub/gnu/ncurses/ncurses-5.7.tar.gz
pkg-config-0.23.tar.gz:
  :md5: 
  :path_prefix: packages/pkgconfig/
  :url: http://pkgconfig.freedesktop.org/releases/pkg-config-0.23.tar.gz
gettext-0.17.tar.gz:
  :md5: 
  :path_prefix: packages/gettext/
  :url: ftp://ftp.gnu.org/pub/gnu/gettext/gettext-0.17.tar.gz
libxml2-2.7.3.tar.gz:
  :md5: 
  :path_prefix: packages/libxml2/
  :url: ftp://xmlsoft.org/libxml2/libxml2-2.7.3.tar.gz
glib-2.23.1.tar.gz:
  :md5: 
  :path_prefix: packages/glib/
  :url: http://ftp.acc.umu.se/pub/gnome/sources/glib/2.23/glib-2.23.1.tar.gz
mono-2.6.1.tar.bz2:
  :md5: 
  :path_prefix: packages/mono/
  :url: http://ftp.novell.com/pub/mono/sources/mono/mono-2.6.1.tar.bz2
